# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
virtualenv:
  system_site_packages: false
os:
  #- osx
  - linux
env:
  - TRAVIS="true" pytest_args="--ignore=tests/test_plotting.py --ignore=tests/test_demos.py"
matrix:
  fast_finish: true
  include:
    - python: 3.8
      env: DISTRIB="ubuntu" COVERAGE="true"
    - env: DISTRIB="conda" PYTHON_VERSION="3.8" COVERAGE="false"
install:
  - source tests/travis_install.sh
before_script:
  - git config --global user.email "patrick.n.raanes@gmail.com"
  - git config --global user.name "Patrick N. Raanes"
script:
  - python setup.py develop
  # flake8 is run by pre-commit
  #- flake8 . --exit-zero # dont fail
  - |
    if [[ "$COVERAGE" == "true" ]]; then
      pre-commit install
      pre-commit run --all-files
      pytest --cov=dapper $pytest_args
    else
      pytest $pytest_args
    fi
after_success:
  - |
    if [[ "$COVERAGE" == "true" ]]; then
       coveralls || echo "failed"
    fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
